In [3]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.stats import norm
import numpy as np
pd.set_option('display.max_columns', None)

In [ ]:
merged_df1=pd.read_csv('/Users/Daniellaviale/Downloads/Dataviz_data_1.csv', index_col=False)

In [ ]:
merged_df1 = merged_df.drop('Unnamed: 0.1', axis=1)
merged_df1 = merged_df.drop('Unnamed: 0', axis=1)
merged_df1 = merged_df.drop('shared_request_flag', axis=1)
merged_df1 = merged_df.drop('shared_match_flag', axis=1)

In [ ]:
merged_df1.to_csv('/Users/Daniellaviale/Downloads/Dataviz_data_v2.csv', index=False)

In [ ]:
##-##

In [4]:
merged_df=pd.read_csv('/Users/Daniellaviale/Downloads/Dataviz_data_v2.csv', index_col=False)

In [5]:
logistic_df = merged_df

In [6]:
logistic_df.head()

,Unnamed: 0,pickup_datetime,dropoff_datetime,PULocationID,DOLocationID,trip_miles,base_passenger_fare,highvolume,LocationID,PUBorough,PUZone,PUservice_zone,hour,day,month
0,0,2022-11-01 00:10:31,2022-11-01 00:17:28,61,61,1.040,7.91,1,61,Brooklyn,Crown Heights North,Boro Zone,0,1,11
1,1,2022-11-01 00:33:47,2022-11-01 00:44:08,61,35,2.350,13.00,1,61,Brooklyn,Crown Heights North,Boro Zone,0,1,11
2,2,2022-11-01 00:22:09,2022-11-01 00:33:42,61,225,1.655,8.92,1,61,Brooklyn,Crown Heights North,Boro Zone,0,1,11
3,3,2022-11-01 00:08:07,2022-11-01 00:36:53,61,219,10.410,33.90,1,61,Brooklyn,Crown Heights North,Boro Zone,0,1,11
4,4,2022-11-01 00:00:35,2022-11-01 00:03:16,61,17,0.515,7.00,1,61,Brooklyn,Crown Heights North,Boro Zone,0,1,11

In [7]:
#Create dummies for the 'PUBorough' column
borough_dummies = pd.get_dummies(logistic_df['PUBorough'])
logistic_df = pd.concat([logistic_df, borough_dummies], axis=1)
logistic_df.drop('PUBorough', axis=1, inplace=True)

In [8]:
#logistic_df.isnull().sum()

In [9]:
logistic_df=logistic_df.drop(['Unnamed: 0'],axis=1)
logistic_df=logistic_df.drop(['month'],axis=1)

In [10]:
#logistic_df['day'].value_counts()

In [11]:
day_map = {1: 'Monday', 2: 'Tuesday', 3: 'Wednesday', 4: 'Thursday',
           5: 'Friday', 6: 'Saturday', 0: 'Sunday'}

# replace values in the day column using the dictionary
logistic_df['day'] = logistic_df['day'].replace(day_map)

In [12]:
logistic_df['day'].value_counts()

Tuesday      3488241
Monday       3326751
Friday       3234332
Thursday     3011489
Saturday     2846606
Wednesday    2844184
Sunday       2532466
Name: day, dtype: int64

In [13]:
#Create dummies for the 'Day' column
day_dummies = pd.get_dummies(logistic_df['day'])
logistic_df = pd.concat([logistic_df, day_dummies], axis=1)
logistic_df.drop('day', axis=1, inplace=True)

In [14]:
logistic_df['hour'].value_counts()

18    1342605
19    1307948
17    1268724
20    1190797
16    1153098
21    1142408
15    1120211
22    1120097
14    1081656
13    1002442
23     994423
8      967424
12     961043
9      945223
11     919832
10     909872
7      801752
0      740849
6      536883
1      534096
2      354703
5      331012
4      279518
3      277453
Name: hour, dtype: int64

In [15]:
logistic_df.head()

,pickup_datetime,dropoff_datetime,PULocationID,DOLocationID,trip_miles,base_passenger_fare,highvolume,LocationID,PUZone,PUservice_zone,hour,Bronx,Brooklyn,EWR,Manhattan,Queens,Staten Island,Friday,Monday,Saturday,Sunday,Thursday,Tuesday,Wednesday
0,2022-11-01 00:10:31,2022-11-01 00:17:28,61,61,1.040,7.91,1,61,Crown Heights North,Boro Zone,0,0,1,0,0,0,0,0,1,0,0,0,0,0
1,2022-11-01 00:33:47,2022-11-01 00:44:08,61,35,2.350,13.00,1,61,Crown Heights North,Boro Zone,0,0,1,0,0,0,0,0,1,0,0,0,0,0
2,2022-11-01 00:22:09,2022-11-01 00:33:42,61,225,1.655,8.92,1,61,Crown Heights North,Boro Zone,0,0,1,0,0,0,0,0,1,0,0,0,0,0
3,2022-11-01 00:08:07,2022-11-01 00:36:53,61,219,10.410,33.90,1,61,Crown Heights North,Boro Zone,0,0,1,0,0,0,0,0,1,0,0,0,0,0
4,2022-11-01 00:00:35,2022-11-01 00:03:16,61,17,0.515,7.00,1,61,Crown Heights North,Boro Zone,0,0,1,0,0,0,0,0,1,0,0,0,0,0

In [16]:
hour_map = {0: 'Midnight', 1: 'Midnight', 2: 'Midnight', 3: 'Midnight', 4: 'Morning', 5: 'Morning', 6: 'Morning', 7: 'Morning',
           8: 'Mid_morning', 9: 'Mid_morning', 10: 'Mid_morning', 11: 'Mid_morning', 12: 'Midday', 13: 'Midday', 14: 'Midday', 15: 'Midday',
        16: 'Evening', 17: 'Evening', 18: 'Evening', 19: 'Evening', 20: 'Night', 21: 'Night', 22: 'Night', 23: 'Night'}

# replace values in the day column using the dictionary
logistic_df['hour'] = logistic_df['hour'].replace(hour_map)
logistic_df.drop('hour', axis=1, inplace=True)

#Midnight: 0, 1, 2, 3
#Morning: 4, 5, 6, 7
#Mid_morning: 8, 9, 10, 11
#Midday: 12, 13, 14, 15
#Evening: 16, 17, 18, 19
#Night: 20, 21, 22, 23

In [17]:
#Create dummies for the 'Hour' column
hour_dummies = pd.get_dummies(logistic_df['hour'])
logistic_df = pd.concat([logistic_df, hour_dummies], axis=1)
#logistic_df.drop('hour', axis=1, inplace=True)

In [18]:
logistic_df['hour'].value_counts()

Evening        5072375
Night          4447725
Midday         4165352
Mid_morning    3742351
Morning        1949165
Midnight       1907101
Name: hour, dtype: int64

In [54]:
#Using Staten Island, Midnight, Sunday as base category
x=logistic_df[['trip_miles','base_passenger_fare','Morning','Mid_morning','Midday','Night','Evening','Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Bronx','Brooklyn','EWR', 'Manhattan','Queens']]
y=logistic_df['highvolume']

##train test split
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test= train_test_split(x,y, test_size=0.3, random_state=101)

#Implementing the Log Model
from sklearn.linear_model import LogisticRegression #import
logmodel=LogisticRegression(solver='liblinear') #initialize
logmodel.fit(x_train,y_train)#fit

logmodel.intercept_ #bo
logmodel.coef_ #b1

probabilities=logmodel.predict_proba(x_test)
y_pred=logmodel.predict(x_test)

##evaluate the model using f1-score
from sklearn.metrics import f1_score
f1_score(y_test,y_pred)

0.9332798430262964

In [55]:
from sklearn.metrics import (accuracy_score, precision_score,recall_score,f1_score,confusion_matrix)

In [56]:
accuracy_score(y_test,y_pred)

0.8812031721376598

In [57]:
precision_score(y_test,y_pred)

0.8926343011360577

In [58]:
recall_score(y_test,y_pred)

0.977803511376827

In [59]:
from scipy.stats import norm
import numpy as np
# create a DataFrame to store the feature names, coefficients, and p-values
coef_df = pd.DataFrame({'feature': x.columns, 'coefficient': logmodel.coef_[0]})

# calculate the p-values for each coefficient using the normal distribution
coef_df['p-value'] = [2 * (1 - norm.cdf(np.abs(x))) for x in logmodel.coef_[0]]

# print the coefficients, p-values, and significance levels (alpha=0.05) next to the feature names
for idx, row in coef_df.iterrows():
    if row['p-value'] < 0.05:
        signif = '*'
    else:
        signif = ''
    print(f"{row['feature']}: {row['coefficient']:.3f} (p-value={row['p-value']:.3f}{signif})")

trip_miles: -0.483 (p-value=0.629)
base_passenger_fare: 0.199 (p-value=0.842)
Morning: -0.033 (p-value=0.974)
Mid_morning: -0.753 (p-value=0.452)
Midday: -1.136 (p-value=0.256)
Night: -0.481 (p-value=0.630)
Evening: -0.990 (p-value=0.322)
Monday: -0.190 (p-value=0.849)
Tuesday: -0.156 (p-value=0.876)
Wednesday: -0.123 (p-value=0.902)
Thursday: 0.027 (p-value=0.978)
Friday: 0.122 (p-value=0.903)
Saturday: 0.148 (p-value=0.883)
Bronx: 0.808 (p-value=0.419)
Brooklyn: -0.694 (p-value=0.488)
EWR: -14.071 (p-value=0.000*)
Manhattan: -5.473 (p-value=0.000*)
Queens: -3.480 (p-value=0.001*)

In [19]:
manhattan_df = logistic_df[logistic_df['Manhattan'] == 1]

In [50]:
manhattan_df['highvolume'].value_counts()

1    7586146
0    2875999
Name: highvolume, dtype: int64

In [61]:
unique_puzone = logistic_df['PUZone'].unique()
print(unique_puzone)

['Crown Heights North' 'Seaport' 'Park Slope' 'Gramercy' 'Central Harlem'
 'Highbridge' 'Melrose South' 'East Flushing' 'East Elmhurst'
 'East Village' 'Laurelton' 'Rockaway Park' 'West Chelsea/Hudson Yards'
 'Washington Heights South' 'Van Nest/Morris Park' 'Mount Hope'
 'Coney Island' 'Brighton Beach' 'Bushwick South' 'Maspeth' 'Saint Albans'
 'Kew Gardens Hills' 'Bayside' 'Battery Park City'
 'Two Bridges/Seward Park' 'West Village' 'Yorkville West' 'Midtown North'
 'Midtown South' 'Bushwick North' 'Williamsburg (North Side)'
 'Hamilton Heights' 'Chinatown' 'East Chelsea' 'Lower East Side'
 'Upper West Side South' 'Long Island City/Hunters Point'
 'Sutton Place/Turtle Bay North' 'JFK Airport' 'Midtown Center' 'Astoria'
 'Forest Hills' 'Williamsburg (South Side)' 'East Williamsburg'
 'Fort Greene' 'Upper East Side North' 'Soundview/Bruckner'
 'Sunset Park East' 'Heartland Village/Todt Hill' 'Upper East Side South'
 'Times Sq/Theatre District' 'TriBeCa/Civic Center' 'Union Sq'
 'Central Harlem North' 'Boerum Hill' 'Elmhurst' 'Sunnyside'
 'Soundview/Castle Hill' 'East Tremont' 'Norwood' 'Van Cortlandt Village'
 'West Farms/Bronx River' 'Lincoln Square East' 'Mott Haven/Port Morris'
 'Roosevelt Island' 'Long Island City/Queens Plaza' 'Murray Hill'
 'Kips Bay' 'Greenwich Village South' 'Jamaica' 'Hollis'
 'South Ozone Park' 'Kew Gardens' 'Ozone Park'
 'East Concourse/Concourse Village' 'Schuylerville/Edgewater Park'
 'Financial District North' 'Sunset Park West' 'Windsor Terrace'
 'West Concourse' 'Pelham Parkway' 'Hunts Point'
 'Downtown Brooklyn/MetroTech' 'Clinton East' 'Financial District South'
 'LaGuardia Airport' 'Kensington' 'Flatbush/Ditmas Park'
 'East Flatbush/Farragut' 'Rosedale' 'Springfield Gardens North'
 'Prospect Heights' 'Prospect-Lefferts Gardens' 'Greenpoint' 'Gravesend'
 'Sheepshead Bay' 'Lenox Hill West' 'East New York/Pennsylvania Avenue'
 'Brownsville' 'East Flatbush/Remsen Village' 'Lenox Hill East' 'Woodside'
 'Crown Heights South' 'SoHo' 'Midtown East' 'Lincoln Square West'
 'Stuyvesant Heights' 'Jackson Heights' 'Clinton Hill' 'Queens Village'
 'Glen Oaks' 'Flatlands' 'Canarsie' 'Crotona Park East' 'Flatiron'
 'Old Astoria' 'Parkchester' 'Garment District' 'Bedford'
 'DUMBO/Vinegar Hill' 'Little Italy/NoLiTa' 'Cobble Hill'
 'Washington Heights North' 'Meatpacking/West Village West'
 'East Harlem North' 'Upper West Side North' 'Ridgewood'
 'World Trade Center' 'Marine Park/Mill Basin' 'Westerleigh'
 'Mariners Harbor' 'West Brighton' 'College Point' 'Flushing'
 'Penn Station/Madison Sq West' 'Eastchester' 'East New York'
 'Alphabet City' 'Woodhaven' 'South Williamsburg' 'Morningside Heights'
 'East Harlem South' 'Bloomingdale' 'Elmhurst/Maspeth' 'Cypress Hills'
 'UN/Turtle Bay South' 'Greenwich Village North'
 'Spuyten Duyvil/Kingsbridge' 'Manhattan Valley'
 'University Heights/Morris Heights' 'South Jamaica' 'Belmont'
 'Brooklyn Heights' 'Rego Park' 'Middle Village' 'Inwood' 'Clinton West'
 'Bensonhurst West' 'Glendale' 'Steinway' 'Briarwood/Jamaica Hills'
 'Westchester Village/Unionport' 'North Corona' 'Whitestone'
 'Murray Hill-Queens' 'Hillcrest/Pomonok' 'Bay Ridge' 'Erasmus'
 'Claremont/Bathgate' 'Kingsbridge Heights' 'Williamsbridge/Olinville'
 'Jamaica Estates' 'Fresh Meadows' 'Bloomfield/Emerson Hill' 'Marble Hill'
 'Stuy Town/Peter Cooper Village' 'Corona' 'Gowanus' 'Morrisania/Melrose'
 'Richmond Hill' 'Springfield Gardens South' 'Far Rockaway' 'Homecrest'
 'Arrochar/Fort Wadsworth' 'Woodlawn/Wakefield' 'Co-Op City'
 'Bedford Park' 'Flushing Meadows-Corona Park' 'Ocean Hill'
 'Queensbridge/Ravenswood' 'Longwood' 'Manhattanville' 'Borough Park'
 'Broad Channel' 'Ocean Parkway South' 'Hudson Sq' 'Dyker Heights'
 'Arden Heights' 'Brooklyn Navy Yard' 'Cambria Heights' 'Bath Beach'
 'Highbridge Park' 'Fordham South' 'Van Cortlandt Park'
 'Grymes Hill/Clifton' 'Baisley Park' 'Midwood' 'Manhattan Beach'
 'Starrett City' 'Bronx Park' 'Carroll Gardens' 'Howard Beach' 'Bronxdale'
 'Madison' 'Queensboro Hill' 'Red Hook' 'Hammels/Arverne'
 'Riverdale/North Riverdale/Fieldston' 'Yorkville East' 'Central Park'
 'Bensonhurst East' 'Pelham Bay' 'Bellerose' 'Stapleton'
 'South Beach/Dongan Hills' 'Allerton/Pelham Gardens' 'Douglaston'
 'Forest Park/Highland Park' 'Bay Terrace/Fort Totten'
 'Saint George/New Brighton' 'Auburndale' 'Prospect Park'
 'New Dorp/Midland Beach' 'Rossville/Woodrow' 'Great Kills' 'City Island'
 'Charleston/Tottenville' 'Oakwood' 'Columbia Street' 'Pelham Bay Park'
 'Port Richmond' 'Inwood Hill Park' 'Oakland Gardens' 'Country Club'
 'Crotona Park' 'Freshkills Park' "Eltingville/Annadale/Prince's Bay"
 'Saint Michaels Cemetery/Woodside' 'Green-Wood Cemetery'
 'Breezy Point/Fort Tilden/Riis Beach' 'Marine Park/Floyd Bennett Field'
 'Randalls Island' 'Astoria Park' 'Battery Park' 'Jamaica Bay'
 'Willets Point' 'Newark Airport' 'Rikers Island' 'Great Kills Park'
 "Governor's Island/Ellis Island/Liberty Island"]

In [20]:
#Create dummies for the 'PUzone' column
puzone_dummies = pd.get_dummies(manhattan_df['PUZone'])
manhattan_df = pd.concat([manhattan_df, puzone_dummies], axis=1)
manhattan_df.drop('PUZone', axis=1, inplace=True)

In [63]:
manhattan_df.head()

,pickup_datetime,dropoff_datetime,PULocationID,DOLocationID,trip_miles,base_passenger_fare,highvolume,LocationID,PUservice_zone,hour,Bronx,Brooklyn,EWR,Manhattan,Queens,Staten Island,Friday,Monday,Saturday,Sunday,Thursday,Tuesday,Wednesday,Evening,Mid_morning,Midday,Midnight,Morning,Night,Alphabet City,Battery Park,Battery Park City,Bloomingdale,Central Harlem,Central Harlem North,Central Park,Chinatown,Clinton East,Clinton West,East Chelsea,East Harlem North,East Harlem South,East Village,Financial District North,Financial District South,Flatiron,Garment District,Governor's Island/Ellis Island/Liberty Island,Gramercy,Greenwich Village North,Greenwich Village South,Hamilton Heights,Highbridge Park,Hudson Sq,Inwood,Inwood Hill Park,Kips Bay,Lenox Hill East,Lenox Hill West,Lincoln Square East,Lincoln Square West,Little Italy/NoLiTa,Lower East Side,Manhattan Valley,Manhattanville,Marble Hill,Meatpacking/West Village West,Midtown Center,Midtown East,Midtown North,Midtown South,Morningside Heights,Murray Hill,Penn Station/Madison Sq West,Randalls Island,Roosevelt Island,Seaport,SoHo,Stuy Town/Peter Cooper Village,Sutton Place/Turtle Bay North,Times Sq/Theatre District,TriBeCa/Civic Center,Two Bridges/Seward Park,UN/Turtle Bay South,Union Sq,Upper East Side North,Upper East Side South,Upper West Side North,Upper West Side South,Washington Heights North,Washington Heights South,West Chelsea/Hudson Yards,West Village,World Trade Center,Yorkville East,Yorkville West
232975,2022-11-01 00:46:33,2022-11-01 00:58:18,209,79,2.07,14.48,1,209,Yellow Zone,Midnight,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
232976,2022-11-01 00:56:16,2022-11-01 01:06:09,209,13,0.91,9.55,1,209,Yellow Zone,Midnight,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
232977,2022-11-01 00:40:06,2022-11-01 00:53:16,209,249,2.36,26.92,1,209,Yellow Zone,Midnight,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
232978,2022-11-01 00:19:58,2022-11-01 00:39:58,209,50,4.33,21.12,1,209,Yellow Zone,Midnight,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
232979,2022-11-01 00:12:16,2022-11-01 00:25:28,209,148,1.61,16.10,1,209,Yellow Zone,Midnight,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [21]:
manhattan_df = manhattan_df.rename(columns={'Governor\'s Island/Ellis Island/Liberty Island': 'Governors Island/Ellis Island/Liberty Island'})

In [22]:
#Using Yorkville West, Midnight, and Sunday as base category
x=manhattan_df[['trip_miles','base_passenger_fare','Morning','Mid_morning','Midday','Night','Evening','Monday','Tuesday','Wednesday','Thursday', 'Friday', 'Saturday','Alphabet City', 'Battery Park', 'Battery Park City', 'Bloomingdale', 'Central Harlem', 'Central Harlem North', 'Central Park', 'Chinatown', 'Clinton East', 'Clinton West', 'East Chelsea', 'East Harlem North', 'East Harlem South', 'East Village', 'Financial District North', 'Financial District South', 'Flatiron', 'Garment District', 'Governors Island/Ellis Island/Liberty Island', 'Gramercy', 'Greenwich Village North', 'Greenwich Village South', 'Hamilton Heights', 'Highbridge Park', 'Hudson Sq', 'Inwood', 'Inwood Hill Park', 'Kips Bay', 'Lenox Hill East', 'Lenox Hill West', 'Lincoln Square East', 'Lincoln Square West', 'Little Italy/NoLiTa', 'Lower East Side', 'Manhattan Valley', 'Manhattanville', 'Marble Hill', 'Meatpacking/West Village West', 'Midtown Center', 'Midtown East', 'Midtown North', 'Midtown South', 'Morningside Heights', 'Murray Hill', 'Penn Station/Madison Sq West', 'Randalls Island', 'Roosevelt Island', 'Seaport', 'SoHo', 'Stuy Town/Peter Cooper Village', 'Sutton Place/Turtle Bay North', 'Times Sq/Theatre District', 'TriBeCa/Civic Center', 'Two Bridges/Seward Park', 'UN/Turtle Bay South', 'Union Sq', 'Upper East Side North', 'Upper East Side South', 'Upper West Side North', 'Upper West Side South', 'Washington Heights North', 'Washington Heights South', 'West Chelsea/Hudson Yards', 'West Village', 'World Trade Center', 'Yorkville East']]
y=manhattan_df['highvolume']

##train test split
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test= train_test_split(x,y, test_size=0.3, random_state=101)

#Implementing the Log Model
from sklearn.linear_model import LogisticRegression #import
logmodel=LogisticRegression(solver='liblinear') #initialize
logmodel.fit(x_train,y_train)#fit

logmodel.intercept_ #bo
logmodel.coef_ #b1

probabilities=logmodel.predict_proba(x_test)
y_pred=logmodel.predict(x_test)

##evaluate the model using f1-score
from sklearn.metrics import f1_score
f1_score(y_test,y_pred)

0.8892092851522461

In [22]:
accuracy_score(y_test,y_pred)

0.8293724933442594

In [23]:
precision_score(y_test,y_pred)

0.8626229564204406

In [24]:
recall_score(y_test,y_pred)

0.9095807541417168

In [23]:
from scipy.stats import norm
import numpy as np
# create a DataFrame to store the feature names, coefficients, and p-values
coef_df = pd.DataFrame({'feature': x.columns, 'coefficient': logmodel.coef_[0]})

# calculate the p-values for each coefficient using the normal distribution
coef_df['p-value'] = [2 * (1 - norm.cdf(np.abs(x))) for x in logmodel.coef_[0]]

# print the coefficients, p-values, and significance levels (alpha=0.05) next to the feature names
for idx, row in coef_df.iterrows():
    if row['p-value'] < 0.05:
        signif = '*'
    else:
        signif = ''
    print(f"{row['feature']}: {row['coefficient']:.3f} (p-value={row['p-value']:.3f}{signif})")

trip_miles: -0.649 (p-value=0.517)
base_passenger_fare: 0.287 (p-value=0.774)
Morning: 0.011 (p-value=0.991)
Mid_morning: -0.743 (p-value=0.458)
Midday: -1.159 (p-value=0.246)
Night: -0.355 (p-value=0.723)
Evening: -0.970 (p-value=0.332)
Monday: -0.311 (p-value=0.756)
Tuesday: -0.305 (p-value=0.760)
Wednesday: -0.325 (p-value=0.745)
Thursday: -0.126 (p-value=0.900)
Friday: -0.048 (p-value=0.962)
Saturday: 0.072 (p-value=0.943)
Alphabet City: 2.116 (p-value=0.034*)
Battery Park: 0.048 (p-value=0.962)
Battery Park City: 0.674 (p-value=0.501)
Bloomingdale: 0.534 (p-value=0.593)
Central Harlem: 2.317 (p-value=0.021*)
Central Harlem North: 3.908 (p-value=0.000*)
Central Park: -1.251 (p-value=0.211)
Chinatown: 1.765 (p-value=0.078)
Clinton East: -0.070 (p-value=0.945)
Clinton West: 1.004 (p-value=0.315)
East Chelsea: 0.020 (p-value=0.984)
East Harlem North: 2.605 (p-value=0.009*)
East Harlem South: 1.377 (p-value=0.168)
East Village: 0.374 (p-value=0.708)
Financial District North: 0.986 (p-value=0.324)
Financial District South: 0.742 (p-value=0.458)
Flatiron: 0.142 (p-value=0.887)
Garment District: -0.279 (p-value=0.780)
Governors Island/Ellis Island/Liberty Island: 0.005 (p-value=0.996)
Gramercy: 0.089 (p-value=0.929)
Greenwich Village North: 0.256 (p-value=0.798)
Greenwich Village South: 0.264 (p-value=0.792)
Hamilton Heights: 3.123 (p-value=0.002*)
Highbridge Park: 2.198 (p-value=0.028*)
Hudson Sq: 0.483 (p-value=0.629)
Inwood: 5.311 (p-value=0.000*)
Inwood Hill Park: 3.105 (p-value=0.002*)
Kips Bay: 0.497 (p-value=0.619)
Lenox Hill East: 0.090 (p-value=0.929)
Lenox Hill West: -0.063 (p-value=0.949)
Lincoln Square East: -0.380 (p-value=0.704)
Lincoln Square West: 0.485 (p-value=0.628)
Little Italy/NoLiTa: 0.755 (p-value=0.450)
Lower East Side: 0.883 (p-value=0.377)
Manhattan Valley: 0.265 (p-value=0.791)
Manhattanville: 2.658 (p-value=0.008*)
Marble Hill: 4.622 (p-value=0.000*)
Meatpacking/West Village West: 0.574 (p-value=0.566)
Midtown Center: -0.430 (p-value=0.667)
Midtown East: -0.431 (p-value=0.666)
Midtown North: -0.315 (p-value=0.753)
Midtown South: 0.125 (p-value=0.901)
Morningside Heights: 1.151 (p-value=0.250)
Murray Hill: -0.039 (p-value=0.969)
Penn Station/Madison Sq West: -0.722 (p-value=0.471)
Randalls Island: 1.622 (p-value=0.105)
Roosevelt Island: 3.268 (p-value=0.001*)
Seaport: 1.263 (p-value=0.207)
SoHo: 0.627 (p-value=0.531)
Stuy Town/Peter Cooper Village: 1.696 (p-value=0.090)
Sutton Place/Turtle Bay North: 0.015 (p-value=0.988)
Times Sq/Theatre District: -0.219 (p-value=0.827)
TriBeCa/Civic Center: 0.715 (p-value=0.475)
Two Bridges/Seward Park: 2.473 (p-value=0.013*)
UN/Turtle Bay South: 0.408 (p-value=0.683)
Union Sq: 0.111 (p-value=0.912)
Upper East Side North: -0.438 (p-value=0.661)
Upper East Side South: -0.489 (p-value=0.625)
Upper West Side North: 0.006 (p-value=0.995)
Upper West Side South: -0.236 (p-value=0.813)
Washington Heights North: 4.979 (p-value=0.000*)
Washington Heights South: 3.962 (p-value=0.000*)
West Chelsea/Hudson Yards: 0.480 (p-value=0.631)
West Village: 0.110 (p-value=0.912)
World Trade Center: 0.447 (p-value=0.655)
Yorkville East: 0.157 (p-value=0.875)

In [30]:
ewr_df = logistic_df[logistic_df['EWR'] == 1]

In [31]:
unique_puzone = ewr_df['PUZone'].unique()
print(unique_puzone)

['Newark Airport']

In [32]:
ewr_df['highvolume'].value_counts()

0    879
1      3
Name: highvolume, dtype: int64

In [37]:
#Using Yorkville West as base category
x=ewr_df[['trip_miles','base_passenger_fare','hour','Morning','Mid_morning','Midday','Night','Evening','Monday','Tuesday','Wednesday','Thursday', 'Friday', 'Saturday']]
y=ewr_df['highvolume']

##train test split
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test= train_test_split(x,y, test_size=0.3, random_state=101)

#Implementing the Log Model
from sklearn.linear_model import LogisticRegression #import
logmodel=LogisticRegression(solver='liblinear') #initialize
logmodel.fit(x_train,y_train)#fit

logmodel.intercept_ #bo
logmodel.coef_ #b1

probabilities=logmodel.predict_proba(x_test)
y_pred=logmodel.predict(x_test)

##evaluate the model using f1-score
from sklearn.metrics import f1_score
f1_score(y_test,y_pred)

0.0

In [24]:
queens_df = logistic_df[logistic_df['Queens'] == 1]

In [28]:
unique_puzone = queens_df['PUZone'].unique()
print(unique_puzone)

['East Flushing' 'East Elmhurst' 'Laurelton' 'Rockaway Park' 'Maspeth'
 'Saint Albans' 'Kew Gardens Hills' 'Bayside'
 'Long Island City/Hunters Point' 'JFK Airport' 'Astoria' 'Forest Hills'
 'Elmhurst' 'Sunnyside' 'Long Island City/Queens Plaza' 'Jamaica' 'Hollis'
 'South Ozone Park' 'Kew Gardens' 'Ozone Park' 'LaGuardia Airport'
 'Rosedale' 'Springfield Gardens North' 'Woodside' 'Jackson Heights'
 'Queens Village' 'Glen Oaks' 'Old Astoria' 'Ridgewood' 'College Point'
 'Flushing' 'Woodhaven' 'Elmhurst/Maspeth' 'South Jamaica' 'Rego Park'
 'Middle Village' 'Glendale' 'Steinway' 'Briarwood/Jamaica Hills'
 'North Corona' 'Whitestone' 'Murray Hill-Queens' 'Hillcrest/Pomonok'
 'Jamaica Estates' 'Fresh Meadows' 'Corona' 'Richmond Hill'
 'Springfield Gardens South' 'Far Rockaway' 'Flushing Meadows-Corona Park'
 'Queensbridge/Ravenswood' 'Broad Channel' 'Cambria Heights'
 'Baisley Park' 'Howard Beach' 'Queensboro Hill' 'Hammels/Arverne'
 'Bellerose' 'Douglaston' 'Forest Park/Highland Park'
 'Bay Terrace/Fort Totten' 'Auburndale' 'Oakland Gardens'
 'Saint Michaels Cemetery/Woodside' 'Breezy Point/Fort Tilden/Riis Beach'
 'Astoria Park' 'Jamaica Bay' 'Willets Point']

In [35]:
queens_df['highvolume'].value_counts()

1    3564593
0     296832
Name: highvolume, dtype: int64

In [25]:
#Create dummies for the 'PUzone' column
puzone_dummies = pd.get_dummies(queens_df['PUZone'])
queens_df = pd.concat([queens_df, puzone_dummies], axis=1)
queens_df.drop('PUZone', axis=1, inplace=True)

In [26]:
queens_df.head()

,pickup_datetime,dropoff_datetime,PULocationID,DOLocationID,trip_miles,base_passenger_fare,highvolume,LocationID,PUservice_zone,hour,Bronx,Brooklyn,EWR,Manhattan,Queens,Staten Island,Friday,Monday,Saturday,Sunday,Thursday,Tuesday,Wednesday,Evening,Mid_morning,Midday,Midnight,Morning,Night,Astoria,Astoria Park,Auburndale,Baisley Park,Bay Terrace/Fort Totten,Bayside,Bellerose,Breezy Point/Fort Tilden/Riis Beach,Briarwood/Jamaica Hills,Broad Channel,Cambria Heights,College Point,Corona,Douglaston,East Elmhurst,East Flushing,Elmhurst,Elmhurst/Maspeth,Far Rockaway,Flushing,Flushing Meadows-Corona Park,Forest Hills,Forest Park/Highland Park,Fresh Meadows,Glen Oaks,Glendale,Hammels/Arverne,Hillcrest/Pomonok,Hollis,Howard Beach,JFK Airport,Jackson Heights,Jamaica,Jamaica Bay,Jamaica Estates,Kew Gardens,Kew Gardens Hills,LaGuardia Airport,Laurelton,Long Island City/Hunters Point,Long Island City/Queens Plaza,Maspeth,Middle Village,Murray Hill-Queens,North Corona,Oakland Gardens,Old Astoria,Ozone Park,Queens Village,Queensboro Hill,Queensbridge/Ravenswood,Rego Park,Richmond Hill,Ridgewood,Rockaway Park,Rosedale,Saint Albans,Saint Michaels Cemetery/Woodside,South Jamaica,South Ozone Park,Springfield Gardens North,Springfield Gardens South,Steinway,Sunnyside,Whitestone,Willets Point,Woodhaven,Woodside
932164,2022-11-01 00:03:52,2022-11-01 00:18:46,73,70,5.268,15.07,1,73,Boro Zone,Midnight,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
932165,2022-11-01 00:44:18,2022-11-01 01:06:45,73,100,11.125,29.08,1,73,Boro Zone,Midnight,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
932166,2022-11-01 00:10:13,2022-11-01 00:13:44,73,92,0.800,8.02,1,73,Boro Zone,Midnight,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
932167,2022-11-01 00:52:14,2022-11-01 00:59:29,73,171,1.486,7.15,1,73,Boro Zone,Midnight,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
932168,2022-11-01 00:52:06,2022-11-01 00:58:20,73,92,1.000,7.91,1,73,Boro Zone,Midnight,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [30]:
#Using Willets Point as base category
x=queens_df[['trip_miles','base_passenger_fare','Morning','Mid_morning','Midday','Night','Evening','Monday','Tuesday','Wednesday','Thursday', 'Friday', 'Saturday', 'East Flushing', 'East Elmhurst', 'Laurelton', 'Rockaway Park', 'Maspeth', 'Saint Albans', 'Kew Gardens Hills','Bayside', 'Long Island City/Hunters Point', 'JFK Airport', 'Astoria', 'Forest Hills', 'Elmhurst', 'Sunnyside', 'Long Island City/Queens Plaza', 'Jamaica', 'Hollis','South Ozone Park', 'Kew Gardens', 'Ozone Park', 'LaGuardia Airport','Rosedale', 'Springfield Gardens North', 'Woodside','Jackson Heights','Queens Village' ,'Glen Oaks', 'Old Astoria', 'Ridgewood', 'College Point','Flushing', 'Woodhaven' ,'Elmhurst/Maspeth', 'South Jamaica', 'Rego Park','Middle Village', 'Glendale', 'Steinway', 'Briarwood/Jamaica Hills','North Corona', 'Whitestone', 'Murray Hill-Queens', 'Hillcrest/Pomonok','Jamaica Estates', 'Fresh Meadows', 'Corona', 'Richmond Hill','Springfield Gardens South', 'Far Rockaway', 'Flushing Meadows-Corona Park','Queensbridge/Ravenswood', 'Broad Channel', 'Cambria Heights','Baisley Park', 'Howard Beach', 'Queensboro Hill', 'Hammels/Arverne','Bellerose', 'Douglaston', 'Forest Park/Highland Park','Bay Terrace/Fort Totten', 'Auburndale', 'Oakland Gardens','Saint Michaels Cemetery/Woodside', 'Breezy Point/Fort Tilden/Riis Beach','Astoria Park', 'Jamaica Bay']]
y=queens_df['highvolume']

##train test split
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test= train_test_split(x,y, test_size=0.3, random_state=101)

#Implementing the Log Model
from sklearn.linear_model import LogisticRegression #import
logmodel=LogisticRegression(solver='liblinear') #initialize
logmodel.fit(x_train,y_train)#fit

logmodel.intercept_ #bo
logmodel.coef_ #b1

probabilities=logmodel.predict_proba(x_test)
y_pred=logmodel.predict(x_test)

##evaluate the model using f1-score
from sklearn.metrics import f1_score
f1_score(y_test,y_pred)

0.9598595030782148

In [32]:
accuracy_score(y_test,y_pred)

0.9229041425103675

In [33]:
precision_score(y_test,y_pred)

0.9243694277882919

In [34]:
recall_score(y_test,y_pred)

0.9981751142423358

In [31]:
from scipy.stats import norm
import numpy as np
# create a DataFrame to store the feature names, coefficients, and p-values
coef_df = pd.DataFrame({'feature': x.columns, 'coefficient': logmodel.coef_[0]})

# calculate the p-values for each coefficient using the normal distribution
coef_df['p-value'] = [2 * (1 - norm.cdf(np.abs(x))) for x in logmodel.coef_[0]]

# print the coefficients, p-values, and significance levels (alpha=0.05) next to the feature names
for idx, row in coef_df.iterrows():
    if row['p-value'] < 0.05:
        signif = '*'
    else:
        signif = ''
    print(f"{row['feature']}: {row['coefficient']:.3f} (p-value={row['p-value']:.3f}{signif})")

trip_miles: -0.105 (p-value=0.916)
base_passenger_fare: 0.049 (p-value=0.961)
Morning: -0.447 (p-value=0.655)
Mid_morning: -0.643 (p-value=0.520)
Midday: -0.879 (p-value=0.379)
Night: -0.441 (p-value=0.659)
Evening: -0.765 (p-value=0.445)
Monday: -0.057 (p-value=0.955)
Tuesday: -0.040 (p-value=0.968)
Wednesday: 0.041 (p-value=0.967)
Thursday: 0.107 (p-value=0.914)
Friday: 0.137 (p-value=0.891)
Saturday: 0.147 (p-value=0.883)
East Flushing: 1.217 (p-value=0.224)
East Elmhurst: -4.065 (p-value=0.000*)
Laurelton: 1.104 (p-value=0.270)
Rockaway Park: 0.232 (p-value=0.816)
Maspeth: -0.140 (p-value=0.889)
Saint Albans: 1.071 (p-value=0.284)
Kew Gardens Hills: 0.285 (p-value=0.776)
Bayside: 1.416 (p-value=0.157)
Long Island City/Hunters Point: -1.191 (p-value=0.234)
JFK Airport: -4.781 (p-value=0.000*)
Astoria: -0.498 (p-value=0.618)
Forest Hills: 0.637 (p-value=0.524)
Elmhurst: 0.511 (p-value=0.609)
Sunnyside: -1.430 (p-value=0.153)
Long Island City/Queens Plaza: -1.889 (p-value=0.059)
Jamaica: 0.420 (p-value=0.675)
Hollis: 1.055 (p-value=0.291)
South Ozone Park: -0.013 (p-value=0.989)
Kew Gardens: -0.391 (p-value=0.695)
Ozone Park: 1.197 (p-value=0.231)
LaGuardia Airport: -4.108 (p-value=0.000*)
Rosedale: 0.907 (p-value=0.365)
Springfield Gardens North: 0.312 (p-value=0.755)
Woodside: -0.464 (p-value=0.642)
Jackson Heights: 0.108 (p-value=0.914)
Queens Village: 1.059 (p-value=0.290)
Glen Oaks: 0.623 (p-value=0.533)
Old Astoria: -0.406 (p-value=0.685)
Ridgewood: 1.605 (p-value=0.108)
College Point: 1.155 (p-value=0.248)
Flushing: 1.222 (p-value=0.222)
Woodhaven: 1.940 (p-value=0.052)
Elmhurst/Maspeth: 0.480 (p-value=0.631)
South Jamaica: -0.317 (p-value=0.751)
Rego Park: 0.415 (p-value=0.678)
Middle Village: 1.134 (p-value=0.257)
Glendale: 1.522 (p-value=0.128)
Steinway: -0.454 (p-value=0.650)
Briarwood/Jamaica Hills: 0.072 (p-value=0.942)
North Corona: 1.420 (p-value=0.156)
Whitestone: 1.169 (p-value=0.243)
Murray Hill-Queens: 1.668 (p-value=0.095)
Hillcrest/Pomonok: 1.332 (p-value=0.183)
Jamaica Estates: 0.622 (p-value=0.534)
Fresh Meadows: 0.803 (p-value=0.422)
Corona: 0.253 (p-value=0.800)
Richmond Hill: 0.092 (p-value=0.927)
Springfield Gardens South: -0.529 (p-value=0.597)
Far Rockaway: 0.802 (p-value=0.423)
Flushing Meadows-Corona Park: -3.048 (p-value=0.002*)
Queensbridge/Ravenswood: -2.886 (p-value=0.004*)
Broad Channel: -0.180 (p-value=0.858)
Cambria Heights: 0.494 (p-value=0.621)
Baisley Park: -1.228 (p-value=0.219)
Howard Beach: 0.782 (p-value=0.434)
Queensboro Hill: 1.345 (p-value=0.179)
Hammels/Arverne: 0.517 (p-value=0.605)
Bellerose: 0.378 (p-value=0.706)
Douglaston: 0.356 (p-value=0.722)
Forest Park/Highland Park: 0.073 (p-value=0.941)
Bay Terrace/Fort Totten: 0.787 (p-value=0.431)
Auburndale: 1.043 (p-value=0.297)
Oakland Gardens: 0.937 (p-value=0.349)
Saint Michaels Cemetery/Woodside: -2.769 (p-value=0.006*)
Breezy Point/Fort Tilden/Riis Beach: 0.051 (p-value=0.959)
Astoria Park: -0.556 (p-value=0.578)
Jamaica Bay: -0.061 (p-value=0.951)